name: Release (build artifacts)

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Build wheel and sdist
        run: |
          python -m pip install --upgrade pip
          python -m pip install build
          python -m build
      - name: Store artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*

